sample_reviews = [
    "I watched this sci-fi blockbuster expecting a mind-blowing experience, and it delivered! The visuals were stunning, and the plot kept me guessing until the end. A must-see for fans of the genre!",
    "This romantic comedy was a total letdown. The jokes fell flat, and the leads had zero chemistry. I was bored halfway through and checked my phone constantly.",
    "What a fantastic animated movie! The story was heartfelt, the animation crisp, and it had just the right amount of humor for both kids and adults. My whole family loved it!",
    "This thriller had so much potential, but the pacing was off, and the twists were predictable. It’s not terrible, but I expected more from such a hyped-up film.",
    "Absolutely loved this historical drama! The costumes, the acting, and the attention to detail were impeccable. It felt like stepping back in time.",
    "This action flick was a mess. The plot made no sense, and the constant explosions couldn’t hide the lack of a coherent story. Save your money.",
    "A brilliant horror movie that kept me on edge the entire time. The creepy atmosphere and subtle scares were perfectly executed. Highly recommend!",
    "I wanted to like this fantasy epic, but the dialogue was cringeworthy, and the characters were so one-dimensional. It felt like a cheap knockoff of better films.",
    "This coming-of-age story was so moving. The young actors were phenomenal, and the script captured the awkwardness of youth perfectly. Brought back memories!",
    "Terrible superhero movie. The CGI was laughable, and the villain’s motivations were nonsensical. I couldn’t wait for it to end.",
    "This mystery thriller was a wild ride! The plot twists were unexpected, and the tension built beautifully. I was glued to my seat!",
    "Such a disappointing sequel. The first film was great, but this one felt like a cash grab with no heart or originality. Skip it.",
    "A gorgeous documentary with stunning visuals and a powerful message. It opened my eyes to issues I hadn’t considered before. Well worth watching.",
    "This comedy was painfully unfunny. The jokes were recycled, and the characters were annoying. I didn’t laugh once.",
    "An incredible sci-fi adventure! The world-building was top-notch, and the lead’s performance carried the emotional weight of the story. Loved it!",
    "The pacing in this drama was glacial. I kept waiting for something to happen, but it just dragged on. Decent acting, but not enough to save it.",
    "Wow, what a fun heist movie! The clever plot and witty banter made it a blast to watch. Perfect for a movie night with friends.",
    "This biopic was so dull. It glossed over the most interesting parts of the subject’s life and felt like a Wikipedia page in movie form.",
    "A heartwarming family film that hit all the right notes. The story was simple but touching, and the kids in the cast were adorable!",
    # "A thrilling ride from start to finish!",
    # "Disappointing plot, but great visuals.",
    # "I couldn’t stop laughing, pure comedy gold!",
    # "Boring and predictable, not worth the ticket.",
    # "An emotional masterpiece, I was in tears.",
    # "The acting was wooden, story fell flat.",
    # "Mind-blowing special effects, a must-see!",
    # "Slow pacing ruined what could’ve been great.",
    # "A heartwarming story that stays with you.",
    # "Terrible dialogue, I cringed throughout.",
    # "Epic action scenes, totally immersive!",
    # "Confusing mess, couldn’t follow the plot.",
    # "A beautiful film, visually stunning!",
    # "Waste of time, nothing redeeming here.",
    # "The chemistry between leads was electric!",
    # "Clichéd and overdone, seen it before.",
    # "A surprisingly deep and moving story.",
    # "Awful, just awful, don’t bother.",
    # "The soundtrack alone made this worth it!",
    # "Overhyped, didn’t live up to the buzz.",
    # "A perfect blend of humor and heart.",
    # "Poorly edited, felt like a rough cut.",
    # "Incredible performances, especially the lead!",
    # "No substance, all style, very shallow.",
    # "A nostalgic gem, loved every minute!",
    # "Dragged on forever, I checked my watch.",
    # "A bold and original take, loved it!",
    # "Cheesy and unoriginal, hard pass.",
    # "The twists kept me on edge, fantastic!",
    # "Flat characters, no emotional connection.",
    # "A visual feast, but the story lacked.",
    # "I walked out halfway, enough said.",
    # "A touching family drama, beautifully done.",
    # "The worst movie I’ve seen this year.",
    # "Edge-of-your-seat suspense, nailed it!",
    # "Too many plot holes to enjoy.",
    # "A fun popcorn flick, nothing deep.",
    # "Horrible pacing, felt like a chore.",
    # "The cinematography was breathtaking!",
    # "Uninspired and forgettable, sadly.",
    # "A hilarious comedy, laughed till I cried!",
    # "No chemistry, no stakes, no fun.",
    # "A powerful story, deeply moving.",
    # "Just a cash grab, no effort made.",
    # "The action never stopped, loved it!",
    # "Confusing and poorly written, ugh.",
    # "A charming rom-com, perfect date movie!",
    # "Overlong and dull, lost my interest.",
    # "The performances carried this film!",
    # "A total flop, don’t waste your time.",
    # "A gripping thriller, kept me guessing!",
    # "Mediocre at best, nothing special.",
    # "A heartfelt story, beautifully told.",
    # "The script was a complete disaster.",
    # "Non-stop fun, perfect summer movie!",
    # "Lacked depth, felt like a TV movie.",
    # "A stunning debut from the director!",
    # "All hype, no substance, very disappointing.",
    # "A rollercoaster of emotions, so good!",
    # "The plot was nonsense, totally lost me.",
    # "Gorgeous visuals, but no heart.",
    # "A complete waste of two hours.",
    # "The cast was phenomenal, carried the film!",
    # "Bland and forgettable, no impact.",
    # "A clever twisty plot, highly recommend!",
    # "Felt like a cheap knockoff, skip it.",
    # "A moving drama, tugged at my heartstrings.",
    # "The humor fell flat, not funny at all.",
    # "A sci-fi epic, absolutely mind-blowing!",
    # "Poorly acted, couldn’t take it seriously.",
    # "A feel-good movie, left me smiling!",
    # "Too convoluted, gave me a headache.",
    # "The action was relentless, so exciting!",
    # "No originality, just a rehash of better films.",
    # "A touching story, beautifully acted.",
    # "The pacing was atrocious, pure boredom.",
    # "A wild ride, couldn’t look away!",
    # "Terrible execution, great idea wasted.",
    # "A heartfelt gem, loved the characters!",
    # "No coherence, just a mess of scenes.",
    # "The visuals were stunning, story so-so.",
    # "A total snoozefest, fell asleep.",
    # "A brilliant satire, so well done!",
    # "Lacked energy, felt lifeless.",
    # "The ending blew me away, incredible!",
    # "A generic action flick, nothing new.",
    # "A touching romance, beautifully shot.",
    # "The writing was lazy, so predictable.",
    # "A fun adventure, great for families!",
    # "No stakes, no tension, no point.",
    # "The score was amazing, elevated the film!",
    # "A disjointed mess, couldn’t connect.",
    # "A hilarious spoof, nailed the comedy!",
    # "Overrated, didn’t live up to the hype.",
    # "A powerful performance by the lead!",
    # "The story was a complete letdown.",
    # "A thrilling mystery, kept me hooked!",
    # "Just awful, couldn’t find one good thing.",
    # "A delightful surprise, exceeded expectations!"
    ]